### ISSUE TITLE
api账户 里没有钱能测试吗？我刚运行了，一堆代码报错

### ISSUE THREAD

**Issue by frankchn-x** [kale5195/automatic-chillout#1]
Franks-MacBook-Pro:automatic-chillout-main Frank$ python3 runpod_api_test.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Frank/Downloads/automatic-chillout-main/runpod_api_test.py", line 47, in <module>
    generation()
  File "/Users/Frank/Downloads/automatic-chillout-main/runpod_api_test.py", line 22, in generation
    task_id = res.json()['id']
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by frankchn-x** [comment]
这是哪里出问题了？虚心请教

**Comment by kale5195** [comment]
没钱没法测试，是按秒计费的，你先充点钱试试
